### ISSUE TITLE
typo spotted on user guide

### ISSUE THREAD

**Issue by zhanghuasg** [WaRP7/WaRP7-User-Guide#23]
User guide manual V1.1 (Sep 16th, 2016):

7.1.2.
$ ums 0 mmc 0

should be :
=> ums 0 mmc 0

With best regards!

**Comment by angolini** [comment]
I can fix it for you, but you can also submit a pull request if you prefer.

**Comment by zhanghuasg** [comment]
I will try to submit one myself.  Thanks.

**Comment by WaRP7** [comment]
For now: $ ums emmc 0
