### ISSUE TITLE
Linux Kernel build for WARP is failing

### ISSUE THREAD

**Issue by ramanalv** [WaRP7/WaRP7-User-Guide#24]
We are trying to deploy Android on warp by following the build instructions listed in https://github.com/marcofrk/WaRP7-User-Guide/blob/0b23e42d4e64db7a3920a9ec65782e9ec844f16e/07-Chapter/Android.adoc

We are able to build Android successfully, however when we try to build linux kernel for it, the build is failing with the following error.

make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-imx_v7_android_defconfig
make: arm-linux-gnueabihf-imx_v7_android_defconfiggcc: Command not found
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  SHIPPED scripts/kconfig/zconf.tab.c
  SHIPPED scripts/kconfig/zconf.lex.c
  SHIPPED scripts/kconfig/zconf.hash.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
scripts/kconfig/conf  --silentoldconfig Kconfig
***
*** Configuration file ".config" not found!
***
*** Please run some configurator (e.g. "make oldconfig" or
*** "make menuconfig" or "make xconfig").
***
make[2]: *** [silentoldconfig] Error 1
make[1]: *** [silentoldconfig] Error 2
make: *** No rule to make target `include/config/auto.conf', needed by `include/config/kernel.release'.  Stop.

Appreciate your help on this.

**Comment by angolini** [comment]
Hi @ramanalv, the link you sent is a fork, and is not exactly part of the WaRP7 project.

You can note Android chapter is not released yet in any WaRP7 User Guide releases. It means we did not finished the instructions for Android which are still under development.

Anyway, the error message you shared `Configuration file ".config" not found!`makes me think if you have a proper environment to develop android and which are the kernel repository you're using.

Please, what the https://github.com/WaRP7/WaRP7-User-Guide repository so you can automatically be notified when we upload the User Guides updates.

**Comment by ramanalv** [comment]
Thanks for your prompt response. Look forward to release of Android Chapter. Do you have any specific timeline this chapter will be released?

 It will be great addition for developers out there to start playing around with this device in conjunction with Android.

**Comment by angolini** [comment]
Hi, @ramanalv. I'm sorry for my delay I'm actually out of office.

I don't know the roadmap for the Android  chapter or the Android itself. Please, what the WaRP7 Github projects.

**Comment by WaRP7** [comment]
please download from https://www.linaro.org/

**Comment by WaRP7** [comment]
please download GCC from https://www.linaro.org/downloads/
Recommend GCC compiler version - “gcc-linaro-4.9-2015.05-x86_64_arm-linux-gnueabihf.tar.xz” and configure the environment as below:
	using tar command to extract GCC source as bellow:
tar xfv gcc-linaro-4.9-2015.05-x86_64_arm-linux-gnueabihf.tar.xz
	setting environment:
export CROSS_COMPILE=`pwd`/gcc-linaro-4.9-2015.05-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-
export ARCH=arm
